#!/bin/sh
# to be called in main extension directory

if [ ! -d po ]; then
  echo "Are you sure you are calling this script from the right location?"
  echo "There is no po directory!"
  exit 1
fi

find . -name '*.js' -print0 | xargs -0 xgettext --from-code=UTF-8 -k_ -kN_ -o po/messages.pot
for i in po/*.po; do
    msgmerge -N $i po/messages.pot > tmp.po
    mv tmp.po $i
done

basename=$(basename $(pwd))

zip  --exclude=*.git* --exclude=*.DS_Store* -r ../$basename.zip .
